const gap=18;
//const centerX=700
//const centerY=400
const centerX=(1536/2)
const centerY=(674/2)
const zoom=1
const widthOfCharecter=13*zoom;
const heightOfCharecter=13*zoom;
export {gap,centerX,centerY,zoom,widthOfCharecter,heightOfCharecter}